# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0006_auto_20180418_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addgoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('longname', models.CharField(max_length=150)),
                ('productimg', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=10, verbose_name='价格')),
                ('marketprice', models.CharField(max_length=10, verbose_name='原价价格')),
                ('storenums', models.IntegerField(verbose_name='库存')),
                ('specifics', models.CharField(max_length=20, verbose_name='规格')),
                ('address', models.CharField(max_length=10, verbose_name='地址')),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='categoryid',
            field=models.CharField(max_length=10, verbose_name='组id'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='childcid',
            field=models.CharField(max_length=10, verbose_name='子类组id'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='childcidname',
            field=models.CharField(max_length=10, verbose_name='子类组名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='dealerid',
            field=models.CharField(max_length=10, verbose_name='详情页id'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='isxf',
            field=models.NullBooleanField(default=False, verbose_name='是否精选'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='marketprice',
            field=models.CharField(max_length=10, verbose_name='原价价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='pmdesc',
            field=models.CharField(max_length=10, verbose_name='是否买一赠一'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.CharField(max_length=10, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='productid',
            field=models.CharField(max_length=10, verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='productimg',
            field=models.CharField(max_length=150, verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='productlongname',
            field=models.CharField(max_length=100, verbose_name='商品长名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='productname',
            field=models.CharField(max_length=50, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='productnum',
            field=models.IntegerField(verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='specifics',
            field=models.CharField(max_length=20, verbose_name='规格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='storenums',
            field=models.IntegerField(verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userAccount',
            field=models.CharField(max_length=20, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userAdderss',
            field=models.CharField(max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userImg',
            field=models.CharField(max_length=150, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=20, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPasswd',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPhone',
            field=models.CharField(max_length=20, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userRank',
            field=models.IntegerField(verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(max_length=32, verbose_name='用户类型'),
        ),
    ]
